




// Generated by PIDL compiler.
// Do not modify this file, but modify the source .pidl file.


#include "battle_c2s_proxy.h"

namespace battle_c2s {


        
	bool Proxy::SpawnEntity ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const int & entity_id)	{
		::Proud::CMessage __msg;
__msg.UseInternalBuffer();
__msg.SetSimplePacketMode(m_core->IsSimplePacketMode());

::Proud::RmiID __msgid=(::Proud::RmiID)Rmi_SpawnEntity;
__msg.Write(__msgid); 
	
__msg << entity_id;
		
		return RmiSend(&remote,1,rmiContext,__msg,
			RmiName_SpawnEntity, (::Proud::RmiID)Rmi_SpawnEntity);
	}

	bool Proxy::SpawnEntity ( ::Proud::HostID *remotes, int remoteCount, ::Proud::RmiContext &rmiContext, const int & entity_id)  	{
		::Proud::CMessage __msg;
__msg.UseInternalBuffer();
__msg.SetSimplePacketMode(m_core->IsSimplePacketMode());

::Proud::RmiID __msgid=(::Proud::RmiID)Rmi_SpawnEntity;
__msg.Write(__msgid); 
	
__msg << entity_id;
		
		return RmiSend(remotes,remoteCount,rmiContext,__msg,
			RmiName_SpawnEntity, (::Proud::RmiID)Rmi_SpawnEntity);
	}
        
	bool Proxy::SkillCommand ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const int & entity_id, const mgg::babkemon::battle::SkillCommandPacket & packet)	{
		::Proud::CMessage __msg;
__msg.UseInternalBuffer();
__msg.SetSimplePacketMode(m_core->IsSimplePacketMode());

::Proud::RmiID __msgid=(::Proud::RmiID)Rmi_SkillCommand;
__msg.Write(__msgid); 
	
__msg << entity_id;
__msg << packet;
		
		return RmiSend(&remote,1,rmiContext,__msg,
			RmiName_SkillCommand, (::Proud::RmiID)Rmi_SkillCommand);
	}

	bool Proxy::SkillCommand ( ::Proud::HostID *remotes, int remoteCount, ::Proud::RmiContext &rmiContext, const int & entity_id, const mgg::babkemon::battle::SkillCommandPacket & packet)  	{
		::Proud::CMessage __msg;
__msg.UseInternalBuffer();
__msg.SetSimplePacketMode(m_core->IsSimplePacketMode());

::Proud::RmiID __msgid=(::Proud::RmiID)Rmi_SkillCommand;
__msg.Write(__msgid); 
	
__msg << entity_id;
__msg << packet;
		
		return RmiSend(remotes,remoteCount,rmiContext,__msg,
			RmiName_SkillCommand, (::Proud::RmiID)Rmi_SkillCommand);
	}
        
	bool Proxy::ItemCommand ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const int & entity_id, const mgg::babkemon::battle::ItemCommandPacket & packet)	{
		::Proud::CMessage __msg;
__msg.UseInternalBuffer();
__msg.SetSimplePacketMode(m_core->IsSimplePacketMode());

::Proud::RmiID __msgid=(::Proud::RmiID)Rmi_ItemCommand;
__msg.Write(__msgid); 
	
__msg << entity_id;
__msg << packet;
		
		return RmiSend(&remote,1,rmiContext,__msg,
			RmiName_ItemCommand, (::Proud::RmiID)Rmi_ItemCommand);
	}

	bool Proxy::ItemCommand ( ::Proud::HostID *remotes, int remoteCount, ::Proud::RmiContext &rmiContext, const int & entity_id, const mgg::babkemon::battle::ItemCommandPacket & packet)  	{
		::Proud::CMessage __msg;
__msg.UseInternalBuffer();
__msg.SetSimplePacketMode(m_core->IsSimplePacketMode());

::Proud::RmiID __msgid=(::Proud::RmiID)Rmi_ItemCommand;
__msg.Write(__msgid); 
	
__msg << entity_id;
__msg << packet;
		
		return RmiSend(remotes,remoteCount,rmiContext,__msg,
			RmiName_ItemCommand, (::Proud::RmiID)Rmi_ItemCommand);
	}
#ifdef USE_RMI_NAME_STRING
const PNTCHAR* Proxy::RmiName_SpawnEntity =_PNT("SpawnEntity");
#else
const PNTCHAR* Proxy::RmiName_SpawnEntity =_PNT("");
#endif
#ifdef USE_RMI_NAME_STRING
const PNTCHAR* Proxy::RmiName_SkillCommand =_PNT("SkillCommand");
#else
const PNTCHAR* Proxy::RmiName_SkillCommand =_PNT("");
#endif
#ifdef USE_RMI_NAME_STRING
const PNTCHAR* Proxy::RmiName_ItemCommand =_PNT("ItemCommand");
#else
const PNTCHAR* Proxy::RmiName_ItemCommand =_PNT("");
#endif
const PNTCHAR* Proxy::RmiName_First = RmiName_SpawnEntity;

}



