



  
// Generated by PIDL compiler.
// Do not modify this file, but modify the source .pidl file.

#pragma once


#include "battle_c2s_common.h"

namespace battle_c2s {


	class Proxy : public ::Proud::IRmiProxy
	{
	public:
	virtual bool SpawnEntity ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const int & entity_id) PN_SEALED; 
	virtual bool SpawnEntity ( ::Proud::HostID *remotes, int remoteCount, ::Proud::RmiContext &rmiContext, const int & entity_id)   PN_SEALED;  
	virtual bool SkillCommand ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const int & entity_id, const mgg::babkemon::battle::SkillCommandPacket & packet) PN_SEALED; 
	virtual bool SkillCommand ( ::Proud::HostID *remotes, int remoteCount, ::Proud::RmiContext &rmiContext, const int & entity_id, const mgg::babkemon::battle::SkillCommandPacket & packet)   PN_SEALED;  
	virtual bool ItemCommand ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const int & entity_id, const mgg::babkemon::battle::ItemCommandPacket & packet) PN_SEALED; 
	virtual bool ItemCommand ( ::Proud::HostID *remotes, int remoteCount, ::Proud::RmiContext &rmiContext, const int & entity_id, const mgg::babkemon::battle::ItemCommandPacket & packet)   PN_SEALED;  
static const PNTCHAR* RmiName_SpawnEntity;
static const PNTCHAR* RmiName_SkillCommand;
static const PNTCHAR* RmiName_ItemCommand;
static const PNTCHAR* RmiName_First;
		Proxy()
		{
			if(m_signature != 1)
				::Proud::ShowUserMisuseError(::Proud::ProxyBadSignatureErrorText);
		}

		virtual ::Proud::RmiID* GetRmiIDList() PN_OVERRIDE { return g_RmiIDList; } 
		virtual int GetRmiIDListCount() PN_OVERRIDE { return g_RmiIDListCount; }
	};

}



