 





// Generated by PIDL compiler.
// Do not modify this file, but modify the source .pidl file.

using System;
namespace battle_s2c
{
	internal class Common
	{
		// Message ID that replies to each RMI method. 
			public const Nettention.Proud.RmiID SetCooldown = (Nettention.Proud.RmiID)2000+1;
			public const Nettention.Proud.RmiID BattleInfo = (Nettention.Proud.RmiID)2000+2;
			public const Nettention.Proud.RmiID SpawnEntity = (Nettention.Proud.RmiID)2000+3;
			public const Nettention.Proud.RmiID CastSkill = (Nettention.Proud.RmiID)2000+4;
			public const Nettention.Proud.RmiID BattleEnd = (Nettention.Proud.RmiID)2000+5;
			public const Nettention.Proud.RmiID BattleWin = (Nettention.Proud.RmiID)2000+6;
			public const Nettention.Proud.RmiID BattleLose = (Nettention.Proud.RmiID)2000+7;
			public const Nettention.Proud.RmiID Turn = (Nettention.Proud.RmiID)2000+8;
		// List that has RMI ID.
		public static Nettention.Proud.RmiID[] RmiIDList = new Nettention.Proud.RmiID[] {
			SetCooldown,
			BattleInfo,
			SpawnEntity,
			CastSkill,
			BattleEnd,
			BattleWin,
			BattleLose,
			Turn,
		};
	}
}

				 
