 





// Generated by PIDL compiler.
// Do not modify this file, but modify the source .pidl file.

using System;
namespace battle_c2s
{
	internal class Common
	{
		// Message ID that replies to each RMI method. 
			public const Nettention.Proud.RmiID SpawnEntity = (Nettention.Proud.RmiID)2100+1;
			public const Nettention.Proud.RmiID SkillCommand = (Nettention.Proud.RmiID)2100+2;
			public const Nettention.Proud.RmiID ItemCommand = (Nettention.Proud.RmiID)2100+3;
		// List that has RMI ID.
		public static Nettention.Proud.RmiID[] RmiIDList = new Nettention.Proud.RmiID[] {
			SpawnEntity,
			SkillCommand,
			ItemCommand,
		};
	}
}

				 
