
// Generated by PIDL compiler.
// Do not modify this file, but modify the source .pidl file.


#include "battle_c2s_common.h"
namespace battle_c2s {


	::Proud::RmiID g_RmiIDList[] = {
               
		Rmi_SpawnEntity,
               
		Rmi_SkillCommand,
               
		Rmi_ItemCommand,
	};

	int g_RmiIDListCount = 3;

}


