
// Generated by PIDL compiler.
// Do not modify this file, but modify the source .pidl file.


#include "battle_s2c_common.h"
namespace battle_s2c {


	::Proud::RmiID g_RmiIDList[] = {
               
		Rmi_SetCooldown,
               
		Rmi_BattleInfo,
               
		Rmi_SpawnEntity,
               
		Rmi_CastSkill,
               
		Rmi_BattleEnd,
               
		Rmi_BattleWin,
               
		Rmi_BattleLose,
               
		Rmi_Turn,
	};

	int g_RmiIDListCount = 8;

}


