
// Generated by PIDL compiler.
// Do not modify this file, but modify the source .pidl file.


#include "common_c2s_common.h"
namespace common_c2s {


	::Proud::RmiID g_RmiIDList[] = {
               
		Rmi_null_cmd,
	};

	int g_RmiIDListCount = 1;

}


