
// Generated by PIDL compiler.
// Do not modify this file, but modify the source .pidl file.


#include "common_s2c_common.h"
namespace common_s2c {


	::Proud::RmiID g_RmiIDList[] = {
               
		Rmi_Welcome,
               
		Rmi_EnterBattle,
               
		Rmi_EnterField,
               
		Rmi_AddItem,
               
		Rmi_RemoveItem,
               
		Rmi_SetItemAmount,
               
		Rmi_AddBabkemon,
	};

	int g_RmiIDListCount = 7;

}


