
// Generated by PIDL compiler.
// Do not modify this file, but modify the source .pidl file.


#include "common_s2c_common.h"
namespace common_s2c {


	::Proud::RmiID g_RmiIDList[] = {
               
		Rmi_EnterBattle,
               
		Rmi_EnterField,
	};

	int g_RmiIDListCount = 2;

}


