




// Generated by PIDL compiler.
// Do not modify this file, but modify the source .pidl file.


#include "common_s2c_proxy.h"

namespace common_s2c {


        
	bool Proxy::EnterBattle ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const int & battle_id)	{
		::Proud::CMessage __msg;
__msg.UseInternalBuffer();
__msg.SetSimplePacketMode(m_core->IsSimplePacketMode());

::Proud::RmiID __msgid=(::Proud::RmiID)Rmi_EnterBattle;
__msg.Write(__msgid); 
	
__msg << battle_id;
		
		return RmiSend(&remote,1,rmiContext,__msg,
			RmiName_EnterBattle, (::Proud::RmiID)Rmi_EnterBattle);
	}

	bool Proxy::EnterBattle ( ::Proud::HostID *remotes, int remoteCount, ::Proud::RmiContext &rmiContext, const int & battle_id)  	{
		::Proud::CMessage __msg;
__msg.UseInternalBuffer();
__msg.SetSimplePacketMode(m_core->IsSimplePacketMode());

::Proud::RmiID __msgid=(::Proud::RmiID)Rmi_EnterBattle;
__msg.Write(__msgid); 
	
__msg << battle_id;
		
		return RmiSend(remotes,remoteCount,rmiContext,__msg,
			RmiName_EnterBattle, (::Proud::RmiID)Rmi_EnterBattle);
	}
        
	bool Proxy::EnterField ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const int & field_id)	{
		::Proud::CMessage __msg;
__msg.UseInternalBuffer();
__msg.SetSimplePacketMode(m_core->IsSimplePacketMode());

::Proud::RmiID __msgid=(::Proud::RmiID)Rmi_EnterField;
__msg.Write(__msgid); 
	
__msg << field_id;
		
		return RmiSend(&remote,1,rmiContext,__msg,
			RmiName_EnterField, (::Proud::RmiID)Rmi_EnterField);
	}

	bool Proxy::EnterField ( ::Proud::HostID *remotes, int remoteCount, ::Proud::RmiContext &rmiContext, const int & field_id)  	{
		::Proud::CMessage __msg;
__msg.UseInternalBuffer();
__msg.SetSimplePacketMode(m_core->IsSimplePacketMode());

::Proud::RmiID __msgid=(::Proud::RmiID)Rmi_EnterField;
__msg.Write(__msgid); 
	
__msg << field_id;
		
		return RmiSend(remotes,remoteCount,rmiContext,__msg,
			RmiName_EnterField, (::Proud::RmiID)Rmi_EnterField);
	}
#ifdef USE_RMI_NAME_STRING
const PNTCHAR* Proxy::RmiName_EnterBattle =_PNT("EnterBattle");
#else
const PNTCHAR* Proxy::RmiName_EnterBattle =_PNT("");
#endif
#ifdef USE_RMI_NAME_STRING
const PNTCHAR* Proxy::RmiName_EnterField =_PNT("EnterField");
#else
const PNTCHAR* Proxy::RmiName_EnterField =_PNT("");
#endif
const PNTCHAR* Proxy::RmiName_First = RmiName_EnterBattle;

}



