  






// Generated by PIDL compiler.
// Do not modify this file, but modify the source .pidl file.
   
#pragma once


#include "common_c2s_common.h"

     
namespace common_c2s {


	class Stub : public ::Proud::IRmiStub
	{
	public:
               
		virtual bool null_cmd ( ::Proud::HostID, ::Proud::RmiContext& )		{ 
			return false;
		} 

#define DECRMI_common_c2s_null_cmd bool null_cmd ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext ) PN_OVERRIDE

#define DEFRMI_common_c2s_null_cmd(DerivedClass) bool DerivedClass::null_cmd ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext )
#define CALL_common_c2s_null_cmd null_cmd ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext )
#define PARAM_common_c2s_null_cmd ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext )
 
		virtual bool ProcessReceivedMessage(::Proud::CReceivedMessage &pa, void* hostTag) PN_OVERRIDE;
		static const PNTCHAR* RmiName_null_cmd;
		static const PNTCHAR* RmiName_First;
		virtual ::Proud::RmiID* GetRmiIDList() PN_OVERRIDE { return g_RmiIDList; }
		virtual int GetRmiIDListCount() PN_OVERRIDE { return g_RmiIDListCount; }
	};

#ifdef SUPPORTS_CPP11 
	
	class StubFunctional : public Stub 
	{
	public:
               
		std::function< bool ( ::Proud::HostID, ::Proud::RmiContext& ) > null_cmd_Function;
		virtual bool null_cmd ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext ) 
		{ 
			if (null_cmd_Function==nullptr) 
				return true; 
			return null_cmd_Function(remote,rmiContext); 
		}

	};
#endif

}


