



  
// Generated by PIDL compiler.
// Do not modify this file, but modify the source .pidl file.

#pragma once


#include "common_s2c_common.h"

namespace common_s2c {


	class Proxy : public ::Proud::IRmiProxy
	{
	public:
	virtual bool EnterBattle ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const int & battle_id) PN_SEALED; 
	virtual bool EnterBattle ( ::Proud::HostID *remotes, int remoteCount, ::Proud::RmiContext &rmiContext, const int & battle_id)   PN_SEALED;  
	virtual bool EnterField ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const int & field_id) PN_SEALED; 
	virtual bool EnterField ( ::Proud::HostID *remotes, int remoteCount, ::Proud::RmiContext &rmiContext, const int & field_id)   PN_SEALED;  
static const PNTCHAR* RmiName_EnterBattle;
static const PNTCHAR* RmiName_EnterField;
static const PNTCHAR* RmiName_First;
		Proxy()
		{
			if(m_signature != 1)
				::Proud::ShowUserMisuseError(::Proud::ProxyBadSignatureErrorText);
		}

		virtual ::Proud::RmiID* GetRmiIDList() PN_OVERRIDE { return g_RmiIDList; } 
		virtual int GetRmiIDListCount() PN_OVERRIDE { return g_RmiIDListCount; }
	};

}



