 





// Generated by PIDL compiler.
// Do not modify this file, but modify the source .pidl file.

using System;
namespace common_s2c
{
	internal class Common
	{
		// Message ID that replies to each RMI method. 
			public const Nettention.Proud.RmiID Welcome = (Nettention.Proud.RmiID)2400+1;
			public const Nettention.Proud.RmiID EnterBattle = (Nettention.Proud.RmiID)2400+2;
			public const Nettention.Proud.RmiID EnterField = (Nettention.Proud.RmiID)2400+3;
			public const Nettention.Proud.RmiID AddItem = (Nettention.Proud.RmiID)2400+4;
			public const Nettention.Proud.RmiID RemoveItem = (Nettention.Proud.RmiID)2400+5;
			public const Nettention.Proud.RmiID SetItemAmount = (Nettention.Proud.RmiID)2400+6;
			public const Nettention.Proud.RmiID AddBabkemon = (Nettention.Proud.RmiID)2400+7;
		// List that has RMI ID.
		public static Nettention.Proud.RmiID[] RmiIDList = new Nettention.Proud.RmiID[] {
			Welcome,
			EnterBattle,
			EnterField,
			AddItem,
			RemoveItem,
			SetItemAmount,
			AddBabkemon,
		};
	}
}

				 
