




// Generated by PIDL compiler.
// Do not modify this file, but modify the source .pidl file.


#include "common_c2s_proxy.h"

namespace common_c2s {


        
	bool Proxy::null_cmd ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext )	{
		::Proud::CMessage __msg;
__msg.UseInternalBuffer();
__msg.SetSimplePacketMode(m_core->IsSimplePacketMode());

::Proud::RmiID __msgid=(::Proud::RmiID)Rmi_null_cmd;
__msg.Write(__msgid); 
	
		
		return RmiSend(&remote,1,rmiContext,__msg,
			RmiName_null_cmd, (::Proud::RmiID)Rmi_null_cmd);
	}

	bool Proxy::null_cmd ( ::Proud::HostID *remotes, int remoteCount, ::Proud::RmiContext &rmiContext)  	{
		::Proud::CMessage __msg;
__msg.UseInternalBuffer();
__msg.SetSimplePacketMode(m_core->IsSimplePacketMode());

::Proud::RmiID __msgid=(::Proud::RmiID)Rmi_null_cmd;
__msg.Write(__msgid); 
	
		
		return RmiSend(remotes,remoteCount,rmiContext,__msg,
			RmiName_null_cmd, (::Proud::RmiID)Rmi_null_cmd);
	}
#ifdef USE_RMI_NAME_STRING
const PNTCHAR* Proxy::RmiName_null_cmd =_PNT("null_cmd");
#else
const PNTCHAR* Proxy::RmiName_null_cmd =_PNT("");
#endif
const PNTCHAR* Proxy::RmiName_First = RmiName_null_cmd;

}



