 





// Generated by PIDL compiler.
// Do not modify this file, but modify the source .pidl file.

using System;
namespace common_c2s
{
	internal class Common
	{
		// Message ID that replies to each RMI method. 
			public const Nettention.Proud.RmiID null_cmd = (Nettention.Proud.RmiID)2500+1;
		// List that has RMI ID.
		public static Nettention.Proud.RmiID[] RmiIDList = new Nettention.Proud.RmiID[] {
			null_cmd,
		};
	}
}

				 
