
// Generated by PIDL compiler.
// Do not modify this file, but modify the source .pidl file.


#include "field_c2s_common.h"
namespace field_c2s {


	::Proud::RmiID g_RmiIDList[] = {
               
		Rmi_MoveCharacter,
	};

	int g_RmiIDListCount = 1;

}


