




// Generated by PIDL compiler.
// Do not modify this file, but modify the source .pidl file.


#include "field_s2c_proxy.h"

namespace field_s2c {


        
	bool Proxy::Snapshot ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const mgg::babkemon::field::Snapshot & snapshot)	{
		::Proud::CMessage __msg;
__msg.UseInternalBuffer();
__msg.SetSimplePacketMode(m_core->IsSimplePacketMode());

::Proud::RmiID __msgid=(::Proud::RmiID)Rmi_Snapshot;
__msg.Write(__msgid); 
	
__msg << snapshot;
		
		return RmiSend(&remote,1,rmiContext,__msg,
			RmiName_Snapshot, (::Proud::RmiID)Rmi_Snapshot);
	}

	bool Proxy::Snapshot ( ::Proud::HostID *remotes, int remoteCount, ::Proud::RmiContext &rmiContext, const mgg::babkemon::field::Snapshot & snapshot)  	{
		::Proud::CMessage __msg;
__msg.UseInternalBuffer();
__msg.SetSimplePacketMode(m_core->IsSimplePacketMode());

::Proud::RmiID __msgid=(::Proud::RmiID)Rmi_Snapshot;
__msg.Write(__msgid); 
	
__msg << snapshot;
		
		return RmiSend(remotes,remoteCount,rmiContext,__msg,
			RmiName_Snapshot, (::Proud::RmiID)Rmi_Snapshot);
	}
#ifdef USE_RMI_NAME_STRING
const PNTCHAR* Proxy::RmiName_Snapshot =_PNT("Snapshot");
#else
const PNTCHAR* Proxy::RmiName_Snapshot =_PNT("");
#endif
const PNTCHAR* Proxy::RmiName_First = RmiName_Snapshot;

}



