 





// Generated by PIDL compiler.
// Do not modify this file, but modify the source .pidl file.

using System;
namespace field_s2c
{
	internal class Common
	{
		// Message ID that replies to each RMI method. 
			public const Nettention.Proud.RmiID Snapshot = (Nettention.Proud.RmiID)2200+1;
			public const Nettention.Proud.RmiID SpawnEntity = (Nettention.Proud.RmiID)2200+2;
			public const Nettention.Proud.RmiID DespawnEntity = (Nettention.Proud.RmiID)2200+3;
		// List that has RMI ID.
		public static Nettention.Proud.RmiID[] RmiIDList = new Nettention.Proud.RmiID[] {
			Snapshot,
			SpawnEntity,
			DespawnEntity,
		};
	}
}

				 
