




// Generated by PIDL compiler.
// Do not modify this file, but modify the source .pidl file.


#include "field_c2s_proxy.h"

namespace field_c2s {


        
	bool Proxy::MoveCharacter ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const mgg::babkemon::field::CharacterMovePacket & packet)	{
		::Proud::CMessage __msg;
__msg.UseInternalBuffer();
__msg.SetSimplePacketMode(m_core->IsSimplePacketMode());

::Proud::RmiID __msgid=(::Proud::RmiID)Rmi_MoveCharacter;
__msg.Write(__msgid); 
	
__msg << packet;
		
		return RmiSend(&remote,1,rmiContext,__msg,
			RmiName_MoveCharacter, (::Proud::RmiID)Rmi_MoveCharacter);
	}

	bool Proxy::MoveCharacter ( ::Proud::HostID *remotes, int remoteCount, ::Proud::RmiContext &rmiContext, const mgg::babkemon::field::CharacterMovePacket & packet)  	{
		::Proud::CMessage __msg;
__msg.UseInternalBuffer();
__msg.SetSimplePacketMode(m_core->IsSimplePacketMode());

::Proud::RmiID __msgid=(::Proud::RmiID)Rmi_MoveCharacter;
__msg.Write(__msgid); 
	
__msg << packet;
		
		return RmiSend(remotes,remoteCount,rmiContext,__msg,
			RmiName_MoveCharacter, (::Proud::RmiID)Rmi_MoveCharacter);
	}
#ifdef USE_RMI_NAME_STRING
const PNTCHAR* Proxy::RmiName_MoveCharacter =_PNT("MoveCharacter");
#else
const PNTCHAR* Proxy::RmiName_MoveCharacter =_PNT("");
#endif
const PNTCHAR* Proxy::RmiName_First = RmiName_MoveCharacter;

}



