



  
// Generated by PIDL compiler.
// Do not modify this file, but modify the source .pidl file.

#pragma once


#include "field_c2s_common.h"

namespace field_c2s {


	class Proxy : public ::Proud::IRmiProxy
	{
	public:
	virtual bool MoveCharacter ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const mgg::babkemon::field::CharacterMovePacket & packet) PN_SEALED; 
	virtual bool MoveCharacter ( ::Proud::HostID *remotes, int remoteCount, ::Proud::RmiContext &rmiContext, const mgg::babkemon::field::CharacterMovePacket & packet)   PN_SEALED;  
static const PNTCHAR* RmiName_MoveCharacter;
static const PNTCHAR* RmiName_First;
		Proxy()
		{
			if(m_signature != 1)
				::Proud::ShowUserMisuseError(::Proud::ProxyBadSignatureErrorText);
		}

		virtual ::Proud::RmiID* GetRmiIDList() PN_OVERRIDE { return g_RmiIDList; } 
		virtual int GetRmiIDListCount() PN_OVERRIDE { return g_RmiIDListCount; }
	};

}



