
// Generated by PIDL compiler.
// Do not modify this file, but modify the source .pidl file.


#include "field_s2c_common.h"
namespace field_s2c {


	::Proud::RmiID g_RmiIDList[] = {
               
		Rmi_Snapshot,
	};

	int g_RmiIDListCount = 1;

}


